### ISSUE TITLE
0.27版本和0.26版本报同一个错误

### ISSUE THREAD

**Issue by Masefielda** [EFrostBlade/PVZHybrid_Editor#7]
Traceback (most recent call last):
  File "editor.py", line 5827, in <module>
  File "editor.py", line 5590, in mainWindow
  File "PVZ_data.py", line 963, in __init__
AttributeError: 'int' object has no attribute 'read_int'

0.27版本和0.26版本报同一个错误

**Comment by EFrostBlade** [comment]
先打开游戏
